services:
  backend:
    build:
      context: .
    depends_on:
      migrator:
        condition: service_completed_successfully 
    command: "dotnet raptorSlot.dll"
    volumes:
      - ./db:/app/db
    networks:
      - app-network
    ports:
      - 8080:8080
  migrator:
    build:
      context: .
      dockerfile: db/dockerfile
    command: "dotnet ef database update"
    volumes:
      - ./db/:/app/db/

networks:
  app-network:
    driver: bridge
